### ISSUE TITLE
getNumColumns is backwards

### ISSUE THREAD

**Issue by OneHatRepo** [MonstroDev/expo-image-picker-multiple#11]
```
// ImageBrowser.js, line 53:
getNumColumns = orientation => orientation !== ScreenOrientation.Orientation.PORTRAIT_UP ? 4 : 7;
```
This is backwards. If the screen orientation is portrait, then the column count should be 4, not 7.
The code _should_ read
```
getNumColumns = orientation => orientation === ScreenOrientation.Orientation.PORTRAIT_UP ? 4 : 7;
```

**Comment by MonstroDev** [comment]
Hi @OneHatRepo,
I think this is really a mistake and I will fix it today. 
Thanks!

**Comment by MonstroDev** [comment]
Version 1.2.1 with related fix already published!
Thanks!
