### ISSUE TITLE
images not getting properly selected

### ISSUE THREAD

**Issue by IndikaMaligaspe** [MonstroDev/expo-image-picker-multiple#12]
There is an issue in selectImage function in ImageBrowser.js. This is due to line `this.setState({selected: newSelected}`. As setState is asynch, the prepareCallback works before the state is set. In order to avoid this I had to call the prepareCallback inside a callback from setState.

```
  this.setState({selected: newSelected}, () =>{
      this.props.onChange(newSelected.length, () => this.prepareCallback());
    });
```

**Comment by MonstroDev** [comment]
Version 1.2.2 with your fix has been released! 
Thanks!
