### ISSUE TITLE
Screen orientation uses incorrect constants

### ISSUE THREAD

**Issue by OneHatRepo** [MonstroDev/expo-image-picker-multiple#15]
ImageBrowser.js, line 53:

`getNumColumns = orientation => orientation === ScreenOrientation.Orientation.PORTRAIT ? 4 : 7;`

The PORTRAIT constant is not defined on ScreenOrientation.Orientation using recent versions of expo-screen-orientation. More recent versions define PORTRAIT_UP and PORTRAIT_DOWN. By modifying this line to include the newer constants, it should always work:

`getNumColumns = orientation => (orientation === ScreenOrientation.Orientation.PORTRAIT || orientation === ScreenOrientation.Orientation.PORTRAIT_UP || orientation === ScreenOrientation.Orientation.PORTRAIT_DOWN) ? 4 : 7;`

**Comment by MonstroDev** [comment]
Hi @OneHatRepo,
it fixed on version 1.2.3 and already published.
Thanks again!
