### ISSUE TITLE
Image browser is not working on iOS devices(and simulator) when expo sdk 39

### ISSUE THREAD

**Issue by iKoru** [MonstroDev/expo-image-picker-multiple#18]
Hi guys,
I'm trying to use this library on my app, which is based on expo sdk 39.
It works well on android emulator and device, but shows nothing on iOS. 
Even on the snack example on the README page link, when you adjust sdk version to 39, it shows an error and doesn't
 work. 
Please find out the way. THX.

**Comment by MonstroDev** [comment]
Hi @iKoru,
I'm planning update package version and Snack demos in this weekend, sorry for so long.

**Comment by OneHatRepo** [comment]
Not sure if this is related, but after upgrading to SDK39, I can't select more than one image. The ImageBrowser will appear, but after selecting only a single image, it immediately closes and calls the callback.

**Comment by MonstroDev** [comment]
@OneHatRepo, yes, this is a bug and I'm planing to fix it soon. 
Thanks!

**Comment by OneHatRepo** [comment]
Any progress here?

**Comment by OneHatRepo** [comment]
Until this is fixed, reverting back to v1.2.3 helps.

**Comment by TheAlmightyThor** [comment]
Any update yet? having the same issue on iOS

**Comment by MonstroDev** [comment]
Hi guys, I fixed that and published the new package version.
Sorry for taking so long, but shit happens at these time.
Thanks!
