### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by jomar357** [MonstroDev/expo-image-picker-multiple#20]
Can you give me a working example of this as a component? I'm just new to Expo so I can't seem to follow the sample that you gave. Any help will be greatly appreciated. Thanks

**Comment by Hassanjankhan** [comment]
how to start camera is there any solution.? i am stuck on it

**Comment by MonstroDev** [comment]
Hey @jomar357,
I released a new package version and updated Snack demo, and here is - https://snack.expo.io/@monstrodev/expo-image-picker-multiple-full-example
