### ISSUE TITLE
Add video picker support

### ISSUE THREAD

**Issue by gayatrisss** [MonstroDev/expo-image-picker-multiple#24]
The expo Image Picker SDK allows for multiple types of media to be picked: 
https://docs.expo.io/versions/v40.0.0/sdk/imagepicker/#imagepickerlaunchimagelibraryasyncoptions

Wondering if we could get this feature here as well. Thanks! This is a great help.

**Comment by MonstroDev** [comment]
Added to 1.4.0.
Sorry for taking so long.
