### ISSUE TITLE
Expo SDK 40: Snack works fine, local project doesn't load images.

### ISSUE THREAD

**Issue by lucaskniight** [MonstroDev/expo-image-picker-multiple#33]
Hi All,

I am currently trying to build an app and use this wonderful library but I have came across a major flaw. I tried the example snack and made some changes in the snack, ran the code and it worked fine, but when I downloaded the snack and ran yarn install and expo start, the app loaded and when I pressed the button to open the Image Browser it returned 0 images in the image browser and returned 2 warnings related to permissions errors.

I believe this problem is related to #26, #30, #4 & #18

Please let me know if there's any thing I can do to help this run or if you need anymore information.

Thanks in advance.

**Comment by obyno50** [comment]
Hi, to get it to work, use version 1.0.6 and then go to the source file and find ImageBrowser file and replace the  prepareCallback function with below code  

`prepareCallback() {
    const { selected, photos } = this.state;
    const selectedPhotos = selected.map(i => photos[i]);
   // const assetsInfo = Promise.all(selectedPhotos.map(i => MediaLibrary.getAssetInfoAsync(i)));
     this.props.callback(selectedPhotos);
  }`


and then go to ImageBrowserScreen file and replace imagesCallback function wit below code

`
imagesCallback = (photos) => {
    const { navigation } = this.props;
    this.props.navigation.setOptions({
      headerRight: () => this._getHeaderLoader()
    });
     //callback.then(async (photos) => {
		 console.log(2);
	  //console.log(photos);
      const cPhotos = [];
      for(let photo of photos) {
        //const pPhoto = await this._processImageAsync(photo.uri);
        cPhotos.push({
          uri: photo.uri,
          name: photo.filename,
          type: 'image/jpg'
        })
      }
	  console.log(3);
	  console.log(cPhotos);
      navigation.navigate('post_ad', {photos: cPhotos});
    //})
    //.catch((e) => console.log(e));
  };
`

you should be good tom

**Comment by natemartins** [comment]
@obyno50 I followed your answer but got "Missing CAMERA_ROLL permissions" error. Any suggestions? 
I'm running expo bare project

**Comment by dorinaaaaalin** [comment]
> @obyno50 I followed your answer but got "Missing CAMERA_ROLL permissions" error. Any suggestions?
> I'm using the package in an expo bare project

I got similar error. [Unhandled promise rejection: Error: Unrecognized permission: cameraRoll]

**Comment by lucswart** [comment]
I get the same error!

**Comment by obyno50** [comment]
am using expo version 36  sdk, which version are you using.

**Comment by lucswart** [comment]
Version 40

**Comment by obyno50** [comment]
Probably thats why it didn't work for you, were the above solution worked on version 36

**Comment by obyno50** [comment]
Probably thats why it didn't work for you, were the above solution worked on version 36

**Comment by Cholineusz** [comment]
@lucswart @ManchuMakes  Got the same problems on EXPO 40. Permission.CAMERA_ROLL has been replaced by Permission.MEDIA_LIBRARY, so you have to patch sources on your own or wait for fix (https://github.com/MonstroDev/expo-image-picker-multiple/pull/35).

**Comment by MonstroDev** [comment]
Package 1.4.0 is released with Expo SDK 40 support.
Sorry for taking so long.
