### ISSUE TITLE
Issue with permission in sdk40 expo, package does not work

### ISSUE THREAD

**Issue by rosnk** [MonstroDev/expo-image-picker-multiple#37]
getting error implementing this package. 

error: 
 `Unrecognized permission: cameraRoll, please install and link the package expo-media-library, see more at https://github.com/expo/expo/tree/master/packages/expo-media-library]`

tried changing #35 pull request manually but it did not solve the problem. Has #35 pull request been merged?? and has this solved the issue??

**Comment by Seu07** [comment]
any answer for fix? I meet this problem too

**Comment by jonelvinnaorbe** [comment]
same problem here

**Comment by rewdt** [comment]
Same here

**Comment by jonelvinnaorbe** [comment]
> Same here

I just created my own media library using "expo-media-library" and "expo-permissions".

**Comment by lucaskniight** [comment]
You guys should check out #33... exact same issue, has a fix.

**Comment by lucaskniight** [comment]
It looks like the PR has been merged and should work.

**Comment by jonelvinnaorbe** [comment]
> It looks like the PR has been merged and should work.

@lucaskniight Thanks for pointing this out. I'll check it out later.

**Comment by MonstroDev** [comment]
Package 1.4.0 is released with Expo SDK 40 support.
Sorry for taking so long.
