### ISSUE TITLE
expo-permissions v8.0.0 is broken on Expo 35

### ISSUE THREAD

**Issue by fmichenaud** [MonstroDev/expo-image-picker-multiple#4]
Hi,

I'm having issues running this package with Expo 35, since it's shipped with expo-permissions v8.0.0 and appears to be broken on iOS only (Everything is working well on Android though.)

Do you have any viable solution without upgrading Expo's SDK ?

For reference, here's the error thrown when asking for permissions :

[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance

Thanks

**Comment by MonstroDev** [comment]
Hi @fmichenaud,
try using ```expo-image-picker-multiple v1.0.6```, this version without ```expo-permissions```, but it's old one.
Current package version support Expo 36 and 37 (current).

**Comment by fmichenaud** [comment]
Great, I didn't check previous versions of your package, it will do the job !

Thank you.
