### ISSUE TITLE
is there possible to open native platform gallery for select, like in Expo ImagePicker ?

### ISSUE THREAD

**Issue by coldSeattle** [MonstroDev/expo-image-picker-multiple#43]
my issue is, can I open the system UI for selecting images ?
if I can, let me see how, if there are not the feature yet, are you going to add such the feature in the future?

![image](https://user-images.githubusercontent.com/56102448/111438998-f1756e00-8715-11eb-8e5f-b0e1ba823c71.png)

**Comment by lucaskniight** [comment]
These are two different libraries for effectively the same thing. If you want to use the Expo ImagePicker library, you're going to have to follow the instructions for that library.

This library provides the ability to select multiple photos on a non-native image selector, whereas Expo's provides the ability to choose one photo on a native image selector.

Please let me know if this answered your question correctly.

**Comment by coldSeattle** [comment]
Thnx for feedback. 
But, I would say, gonna you add that feature(can selecting multiple photo from the native image system) in the library in the future?

**Comment by lucaskniight** [comment]
It's unlikely, this feature will most likely be included in Expo ImagePicker by Expo.

If we were to support this feature, we would have to write native code (meaning it couldn't be used on Expo apps)

**Comment by coldSeattle** [comment]
Okay, thank u for your answer!
