### ISSUE TITLE
ScreenOrientation error on expo sdk 37.0.0

### ISSUE THREAD

**Issue by skangayam** [MonstroDev/expo-image-picker-multiple#7]
Error:

`[Unhandled promise rejection: TypeError: undefined is not an object (evaluating '_expoScreenOrientation.default.addOrientationChangeListener')]`

The dependencies on my project are
```
    "expo": "^37.0.0",
    "expo-cli": "^3.13.8",
    "expo-image-picker": "~8.1.0",
    "expo-image-picker-multiple": "^1.1.5",
    "expo-multiple-media-imagepicker": "^1.2.1",
```

This error started showing up after I upgraded to expo sdk v 37.0.0

**Comment by skangayam** [comment]
I see that a PR to fix the same issue has been merged to master already
https://github.com/MonstroDev/expo-image-picker-multiple/pull/5

Can a new release be published to include these changes please.

**Comment by MonstroDev** [comment]
Hi @skangayam 
Yes, expect a new version tomorrow.
Thanks

**Comment by SirPhemmiey** [comment]
Hey @MonstroDev @skangayam , any update on this please?

**Comment by MonstroDev** [comment]
Hi @skangayam @SirPhemmiey,
Sorry for delay, version 1.2.0 already published.
Thanks!

**Comment by SirPhemmiey** [comment]
Thanks man. 

But @MonstroDev , I am having one issue. 

How can i access the `onSubmit` function that's inside `updateHandler` function outside the function?. It's really difficult because the library is made to only work with using the ImageBrower component in a header and not in a modal. 

Please help, thanks

**Comment by SirPhemmiey** [comment]
@MonstroDev , count is always right but I always keep getting older assets, Eg. I select one image, there is no object, I deselect the same image, object is logged. Does this have something to do with this being async?
