### ISSUE TITLE
handling videos aswell

### ISSUE THREAD

**Issue by Karnich** [MonstroDev/expo-image-picker-multiple#9]
Hi

Would it be possible to also get videos into the feed?

**Comment by MonstroDev** [comment]
Hi @Karnich
In current package version - no, but you can fork this repo, change only one line of code in `/src/ImageBrowser.js` line 72, from `assetType: 'Photos',` to `assetType: 'Videos',`, and it should work.

Maybe in the next version I will move `assetType` field to the parameters.
Thanks!
